default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: mixed-line-ending
        args: [--fix=no]
    -   id: double-quote-string-fixer
    -   id: pretty-format-json
        args: ['--autofix', '--no-sort-keys', '--indent=4']
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --remove-unused-variables, --in-place]
        exclude: __init__\.py
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.10.1
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--skip-string-normalization]
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        args: ['--max-line-length=120', '--ignore=E203,W503,E731', '--per-file-ignores=__init__.py:F401']
