name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Set up Firebase configuration
        run: cp .firebaserc_dev .firebaserc

      - name: Set up correct firebase.json
        run: cp firebase.dev.json firebase.json

      - name: Install Dependencies
        run: npm install  # or yarn install if you're using Yarn

      - name: Setup .env.production
        run: |
          echo REACT_APP_FIREBASE_AUTH_DOMAIN=${{ env.REACT_APP_FIREBASE_AUTH_DOMAIN }} >> .env.production
          echo REACT_APP_FIREBASE_API_KEY=${{ env.REACT_APP_FIREBASE_API_KEY }} >> .env.production
          echo REACT_APP_FIREBASE_DATABASE_URL=${{ env.REACT_APP_FIREBASE_DATABASE_URL }} >> .env.production
          echo REACT_APP_FIREBASE_PROJECT_ID=${{ env.REACT_APP_FIREBASE_PROJECT_ID }} >> .env.production
          echo REACT_APP_FIREBASE_STORAGE_BUCKET=${{ env.REACT_APP_FIREBASE_STORAGE_BUCKET }} >> .env.production
          echo REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }} >> .env.production
          echo REACT_APP_FIREBASE_APP_ID=${{ env.REACT_APP_FIREBASE_APP_ID }} >> .env.production
          echo REACT_APP_FIREBASE_MEASUREMENT_ID=${{ env.REACT_APP_FIREBASE_MEASUREMENT_ID }} >> .env.production
          echo REACT_APP_FIREBASE_VAPID_KEY=${{ env.REACT_APP_FIREBASE_VAPID_KEY }} >> .env.production
          echo REACT_APP_OPENROUTESERVICE_API_KEY=${{ env.REACT_APP_OPENROUTESERVICE_API_KEY }} >> .env.production
          echo REACT_APP_COMMIT_HASH=${{ env.REACT_APP_COMMIT_HASH }} >> .env.production


      - name: Build Project
        run: npm run build  # or yarn build, adjust based on your build command

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTATODEV }}'
          projectId: portatodev
