name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Set up Firebase configuration
        run: cp .firebaserc_dev .firebaserc

      - name: Set up correct firebase.json
        run: cp firebase.dev.json firebase.json

      - name: Install Dependencies
        run: npm install  # or yarn install if you're using Yarn

      - name: Setup .env.production
        run: |
          echo REACT_APP_FIREBASE_AUTH_DOMAIN=${{ vars.REACT_APP_FIREBASE_AUTH_DOMAIN }} >> .env.production
          echo REACT_APP_FIREBASE_API_KEY=${{ vars.REACT_APP_FIREBASE_API_KEY }} >> .env.production
          echo REACT_APP_FIREBASE_DATABASE_URL=${{ vars.REACT_APP_FIREBASE_DATABASE_URL }} >> .env.production
          echo REACT_APP_FIREBASE_PROJECT_ID=${{ vars.REACT_APP_FIREBASE_PROJECT_ID }} >> .env.production
          echo REACT_APP_FIREBASE_STORAGE_BUCKET=${{ vars.REACT_APP_FIREBASE_STORAGE_BUCKET }} >> .env.production
          echo REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ vars.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }} >> .env.production
          echo REACT_APP_FIREBASE_APP_ID=${{ vars.REACT_APP_FIREBASE_APP_ID }} >> .env.production
          echo REACT_APP_FIREBASE_MEASUREMENT_ID=${{ vars.REACT_APP_FIREBASE_MEASUREMENT_ID }} >> .env.production
          echo REACT_APP_FIREBASE_VAPID_KEY=${{ vars.REACT_APP_FIREBASE_VAPID_KEY }} >> .env.production
          echo REACT_APP_OPENROUTESERVICE_API_KEY=${{ vars.REACT_APP_OPENROUTESERVICE_API_KEY }} >> .env.production
          echo REACT_APP_COMMIT_HASH=${{ vars.REACT_APP_COMMIT_HASH }} >> .env.production
          
      # Displaying the contents of the .env.production for debugging
      - name: Display .env.production
        run: cat .env.production

      - name: Test env var
        run: npm run print-log 

      - name: Build Project
        run: npm run build 

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTATODEV }}'
          projectId: portatodev

      - name: Set up Google Cloud SDK Authentication
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTATODEV }}" > service-account.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./service-account.json

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Install Google Cloud SDK
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get install apt-transport-https ca-certificates
          sudo apt-get install -y curl
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update && sudo apt-get install google-cloud-sdk
        
      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=service-account.json
      
      - name: Get GCP Access Token
        id: gcp-token
        run: echo "::set-output name=token::$(gcloud auth print-access-token)"
      
      - name: Use Firebase with token
        run: firebase use --token "${{ steps.gcp-token.outputs.token }}"
      
      - name: Fetch Firebase Functions Config 
        run: firebase functions:config:get
